// <auto-generated />
using System;
using Generalizacija.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Generalizacija.Migrations
{
    [DbContext(typeof(GeneralizacijaContext))]
    [Migration("20240214101157_newMig")]
    partial class newMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Generalizacija.Entity.Sastanak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sastanak_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Tip sastanka");

                    b.HasKey("Id");

                    b.ToTable("Sastanaks");

                    b.HasDiscriminator<string>("sastanak_type").HasValue("Sastanak");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Generalizacija.Entity.IndividualniSastanak", b =>
                {
                    b.HasBaseType("Generalizacija.Entity.Sastanak");

                    b.Property<string>("nesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("individualni");
                });

            modelBuilder.Entity("Generalizacija.Entity.TimskiSastanak", b =>
                {
                    b.HasBaseType("Generalizacija.Entity.Sastanak");

                    b.Property<Guid?>("Tim")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("razlog")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("timski");
                });
#pragma warning restore 612, 618
        }
    }
}
