// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserMicroservice.Entites;

#nullable disable

namespace UserMicroservice.Migrations
{
    [DbContext(typeof(UserClassContext))]
    [Migration("20240220122708_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserMicroservice.Entites.UserClass", b =>
                {
                    b.Property<Guid>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DatumRegistracije")
                        .HasColumnType("date");

                    b.Property<string>("EmailKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImeKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktKorisnika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrvoLogovanje")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UlogaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KorisnikId");

                    b.HasIndex("EmailKorisnika")
                        .IsUnique();

                    b.HasIndex("UlogaId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            KorisnikId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            DatumRegistracije = new DateOnly(2020, 11, 15),
                            EmailKorisnika = "milos@mail.com",
                            ImeKorisnika = "Milos",
                            KontaktKorisnika = "065777888",
                            LozinkaKorisnika = "VCNlK4EAsI6IlHsXHrCo3PefXRWxB+i5CulkbBrQe5EfJUaVi74Osos+rlHwhkgLuYMKpPD+4OIVcqqGF65Xh36d6xonGkUFgKneetFS/mclT+2/zHOf3hkrvbEM7j3A+CYkcz/4xEMX8wIqB9e374kxAfafiBE3QTotvP95opS7xVSD7RyJLFYhnJGtZm6qWHpeSNxvlv0k4I2nYOJAQoT/MSrj5LwEZuZ4TcWak8Dq/X5iV7XI8Hatp0WOIrrzRPEP3dKqWu3NaRxyD30NQl5WGo/cKgG60Cm3jBYa/mz7LNwh7ReNY3jMdyHHqTUwEQ8bpv4KBDgjE4oSsbb8DQ==",
                            PrezimeKorisnika = "Lukic",
                            PrvoLogovanje = true,
                            Salt = "BW+cL4E0Jg==",
                            TimId = new Guid("6a411c13-a195-48f7-8dbd-67596c399586"),
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397478")
                        });
                });

            modelBuilder.Entity("UserMicroservice.Entites.UserRole", b =>
                {
                    b.Property<Guid>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivUloge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397478"),
                            NazivUloge = "Admin"
                        },
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397123"),
                            NazivUloge = "Product owner"
                        },
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397456"),
                            NazivUloge = "Developer"
                        },
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397222"),
                            NazivUloge = "Scrum master"
                        });
                });

            modelBuilder.Entity("UserMicroservice.Entites.UserClass", b =>
                {
                    b.HasOne("UserMicroservice.Entites.UserRole", "Uloga")
                        .WithMany("UserClasses")
                        .HasForeignKey("UlogaId");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("UserMicroservice.Entites.UserRole", b =>
                {
                    b.Navigation("UserClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
