// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserMicroservice.Entites;

#nullable disable

namespace UserMicroservice.Migrations
{
    [DbContext(typeof(UserClassContext))]
    [Migration("20240210173005_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserMicroservice.Entites.UserClass", b =>
                {
                    b.Property<Guid>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DatumRegistracije")
                        .HasColumnType("date");

                    b.Property<string>("EmailKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImeKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KontaktKorisnika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrvoLogovanje")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UlogaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KorisnikId");

                    b.HasIndex("EmailKorisnika")
                        .IsUnique();

                    b.HasIndex("UlogaId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            KorisnikId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            DatumRegistracije = new DateOnly(2020, 11, 15),
                            EmailKorisnika = "milos@mail.com",
                            ImeKorisnika = "Milos",
                            KalendarId = new Guid("6a411c13-a195-48f7-8dbd-67596c399700"),
                            KontaktKorisnika = "065777888",
                            LozinkaKorisnika = "/u9fSR1udvzFOl0+OlNEyOV5ax+GO5o4laz6RGXQ5bUeDasDvgNOEizA3+MdMMVNd0lehN1XglPJ4fRBqtN/edabeEk9ewDv9cT0i2SCNqpCk1zg9oNflXtOF9sUP9VD4o7bl8eAvfmsY2eSv2gTtFa8QpOqE1Z6G87pCanIUiBnBiRs/UWtBmhHI8uleAd4mC5Hu3nRyOp0TGRmaw993icSH/sOqdDL2OuAr2gUKB3lv3suE022mG2kt+P86p0c8a/SM1N17iwY5NUqbH75zHVEuzXpNYsnsMiHrrdenRH7O/jhNPQWVK8edysMPkZf917zVpwdolcFDB5112S1IQ==",
                            PrezimeKorisnika = "Lukic",
                            PrvoLogovanje = true,
                            Salt = "zcCFz5y1Fw==",
                            TimId = new Guid("6a411c13-a195-48f7-8dbd-67596c399586"),
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397478")
                        });
                });

            modelBuilder.Entity("UserMicroservice.Entites.UserRole", b =>
                {
                    b.Property<Guid>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivUloge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397478"),
                            NazivUloge = "Admin"
                        },
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397123"),
                            NazivUloge = "Product owner"
                        },
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397456"),
                            NazivUloge = "Developer"
                        },
                        new
                        {
                            UlogaId = new Guid("6a411c13-a195-48f7-8dbd-67596c397222"),
                            NazivUloge = "Scrum master"
                        });
                });

            modelBuilder.Entity("UserMicroservice.Entites.UserClass", b =>
                {
                    b.HasOne("UserMicroservice.Entites.UserRole", "Uloga")
                        .WithMany("UserClasses")
                        .HasForeignKey("UlogaId");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("UserMicroservice.Entites.UserRole", b =>
                {
                    b.Navigation("UserClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
